In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Python is working!")
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Matplotlib is building the font cache; this may take a moment.

Python is working!
Pandas version: 3.0.6
NumPy version: 2.5.3

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Project folders
project_dir = Path.cwd().parent
data_dir = project_dir / "data"

# Load dataset
df = pd.read_csv(
    data_dir / "airline_passenger_satisfaction.csv"
)

# Load data dictionary
data_dictionary = pd.read_csv(
    data_dir / "data_dictionary.csv"
)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Shape: (129880, 24)

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,3,5,2,5,5,5,3,5,5,Neutral or Dissatisfied
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,5,4,5,5,3,5,2,5,5,Satisfied
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,3,5,3,5,5,3,4,3,3,Satisfied
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,5,4,4,5,2,5,5,Satisfied
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,3,4,4,5,4,3,3,3,3,Satisfied

In [3]:
print("Column names:")
print(df.columns.tolist())

print("\nMissing values:")
display(df.isnull().sum().sort_values(ascending=False))

print("\nDuplicate rows:", df.duplicated().sum())

Column names:
['ID', 'Gender', 'Age', 'Customer Type', 'Type of Travel', 'Class', 'Flight Distance', 'Departure Delay', 'Arrival Delay', 'Departure and Arrival Time Convenience', 'Ease of Online Booking', 'Check-in Service', 'Online Boarding', 'Gate Location', 'On-board Service', 'Seat Comfort', 'Leg Room Service', 'Cleanliness', 'Food and Drink', 'In-flight Service', 'In-flight Wifi Service', 'In-flight Entertainment', 'Baggage Handling', 'Satisfaction']

Missing values:

Arrival Delay                             393
ID                                          0
Age                                         0
Gender                                      0
Type of Travel                              0
Class                                       0
Flight Distance                             0
Customer Type                               0
Departure Delay                             0
Departure and Arrival Time Convenience      0
Ease of Online Booking                      0
Check-in Service                            0
Online Boarding                             0
Gate Location                               0
On-board Service                            0
Seat Comfort                                0
Leg Room Service                            0
Cleanliness                                 0
Food and Drink                              0
In-flight Service                           0
In-flight Wifi Service                      0
In-flight Entertainment                     0
Baggage Handling                            0
Satisfaction                                0
dtype: int64

Duplicate rows: 0

In [4]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Duplicate rows:", df.duplicated().sum())
print("Unique passenger IDs:", df["ID"].nunique())

Number of rows: 129880
Number of columns: 24
Duplicate rows: 0
Unique passenger IDs: 129880

In [5]:
print(df["Satisfaction"].value_counts())

print("\nSatisfaction percentages:")
display(
    df["Satisfaction"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Satisfaction
Neutral or Dissatisfied    73452
Satisfied                  56428
Name: count, dtype: int64

Satisfaction percentages:

Satisfaction
Neutral or Dissatisfied    56.55
Satisfied                  43.45
Name: proportion, dtype: float64

In [6]:
rating_cols = [
    col for col in df.columns
    if "Service" in col
    or col in [
        "Departure and Arrival Time Convenience",
        "Ease of Online Booking",
        "Gate Location",
        "Online Boarding",
        "Seat Comfort",
        "Leg Room Service",
        "Cleanliness",
        "Food and Drink",
        "Inflight Entertainment",
        "In-flight Wifi Service"
    ]
]

for col in rating_cols:
    print(f"\n{col}")
    print(sorted(df[col].dropna().unique()))

Departure and Arrival Time Convenience
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Ease of Online Booking
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Check-in Service
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Online Boarding
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Gate Location
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

On-board Service
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Seat Comfort
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Leg Room Service
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Cleanliness
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Food and Drink
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In-flight Service
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In-flight Wifi Service
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [7]:
display(data_dictionary)

,Field,Description
0,ID,Unique passenger identifier
1,Gender,Gender of the passenger (Female/Male)
2,Age,Age of the passenger
3,Customer Type,Type of airline customer (First-time/Returning)
4,Type of Travel,Purpose of the flight (Business/Personal)
5,Class,Travel class in the airplane for the passenger...
6,Flight Distance,Flight distance in miles
7,Departure Delay,Flight departure delay in minutes
8,Arrival Delay,Flight arrival delay in minutes
9,Departure and Arrival Time Convenience,Satisfaction level with the convenience of the...
10,Ease of Online Booking,Satisfaction level with the online booking exp...
11,Check-in Service,Satisfaction level with the check-in service f...
12,Online Boarding,Satisfaction level with the online boarding ex...
13,Gate Location,Satisfaction level with the gate location in t...
14,On-board Service,Satisfaction level with the on-boarding servic...
15,Seat Comfort,Satisfaction level with the comfort of the air...
16,Leg Room Service,Satisfaction level with the leg room of the ai...
17,Cleanliness,Satisfaction level with the cleanliness of the...
18,Food and Drink,Satisfaction level with the food and drinks on...
19,In-flight Service,Satisfaction level with the in-flight service ...
20,In-flight Wifi Service,Satisfaction level with the in-flight Wifi ser...
21,In-flight Entertainment,Satisfaction level with the in-flight entertai...
22,Baggage Handling,Satisfaction level with the baggage handling f...
23,Satisfaction,Overall satisfaction level with the airline (S...

In [8]:
print("Dataset shape:", df.shape)

print("\nSatisfaction counts:")
display(df["Satisfaction"].value_counts())

print("\nSatisfaction percentage:")
display(
    (df["Satisfaction"].value_counts(normalize=True) * 100)
    .round(2)
)

Dataset shape: (129880, 24)

Satisfaction counts:

Satisfaction
Neutral or Dissatisfied    73452
Satisfied                  56428
Name: count, dtype: int64

Satisfaction percentage:

Satisfaction
Neutral or Dissatisfied    56.55
Satisfied                  43.45
Name: proportion, dtype: float64

In [9]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate IDs:", df["ID"].duplicated().sum())
print("Missing arrival delays:", df["Arrival Delay"].isna().sum())

Duplicate rows: 0
Duplicate IDs: 0
Missing arrival delays: 393

In [11]:
print("Satisfaction counts:")
display(df["Satisfaction"].value_counts())

print("\nSatisfaction percentages:")
display(
    (df["Satisfaction"].value_counts(normalize=True) * 100)
    .round(2)
)

Satisfaction counts:

Satisfaction
Neutral or Dissatisfied    73452
Satisfied                  56428
Name: count, dtype: int64

Satisfaction percentages:

Satisfaction
Neutral or Dissatisfied    56.55
Satisfied                  43.45
Name: proportion, dtype: float64

In [12]:
print("Dataset shape:", df.shape)
print("Unique passenger IDs:", df["ID"].nunique())
print("Duplicate rows:", df.duplicated().sum())

print("\nMissing values:")
display(
    df.isnull().sum()
    .sort_values(ascending=False)
    .head(10)
)

Dataset shape: (129880, 24)
Unique passenger IDs: 129880
Duplicate rows: 0

Missing values:

Arrival Delay                             393
ID                                          0
Age                                         0
Gender                                      0
Type of Travel                              0
Class                                       0
Flight Distance                             0
Customer Type                               0
Departure Delay                             0
Departure and Arrival Time Convenience      0
dtype: int64