In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

# Locate the project folders
project_dir = Path.cwd().parent
data_dir = project_dir / "data"

# Load the original dataset
df_raw = pd.read_csv(
    data_dir / "airline_passenger_satisfaction.csv"
)

# Create a working copy
df_clean = df_raw.copy()

print("Raw data shape:", df_raw.shape)
print("Working copy shape:", df_clean.shape)

Raw data shape: (129880, 24)
Working copy shape: (129880, 24)

In [2]:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)

print(df_clean.columns.tolist())

['id', 'gender', 'age', 'customer_type', 'type_of_travel', 'class', 'flight_distance', 'departure_delay', 'arrival_delay', 'departure_and_arrival_time_convenience', 'ease_of_online_booking', 'check_in_service', 'online_boarding', 'gate_location', 'on_board_service', 'seat_comfort', 'leg_room_service', 'cleanliness', 'food_and_drink', 'in_flight_service', 'in_flight_wifi_service', 'in_flight_entertainment', 'baggage_handling', 'satisfaction']

In [3]:
print("Shape after renaming:", df_clean.shape)
print("Duplicate rows:", df_clean.duplicated().sum())
print("Missing arrival delays:", df_clean["arrival_delay"].isna().sum())

display(df_clean.head())

Shape after renaming: (129880, 24)
Duplicate rows: 0
Missing arrival delays: 393

,id,gender,age,customer_type,type_of_travel,class,flight_distance,departure_delay,arrival_delay,departure_and_arrival_time_convenience,...,on_board_service,seat_comfort,leg_room_service,cleanliness,food_and_drink,in_flight_service,in_flight_wifi_service,in_flight_entertainment,baggage_handling,satisfaction
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,3,5,2,5,5,5,3,5,5,Neutral or Dissatisfied
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,5,4,5,5,3,5,2,5,5,Satisfied
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,3,5,3,5,5,3,4,3,3,Satisfied
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,5,4,4,5,2,5,5,Satisfied
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,3,4,4,5,4,3,3,3,3,Satisfied

In [4]:
data_dictionary = pd.read_csv(
    data_dir / "data_dictionary.csv"
)

display(data_dictionary)

,Field,Description
0,ID,Unique passenger identifier
1,Gender,Gender of the passenger (Female/Male)
2,Age,Age of the passenger
3,Customer Type,Type of airline customer (First-time/Returning)
4,Type of Travel,Purpose of the flight (Business/Personal)
5,Class,Travel class in the airplane for the passenger...
6,Flight Distance,Flight distance in miles
7,Departure Delay,Flight departure delay in minutes
8,Arrival Delay,Flight arrival delay in minutes
9,Departure and Arrival Time Convenience,Satisfaction level with the convenience of the...
10,Ease of Online Booking,Satisfaction level with the online booking exp...
11,Check-in Service,Satisfaction level with the check-in service f...
12,Online Boarding,Satisfaction level with the online boarding ex...
13,Gate Location,Satisfaction level with the gate location in t...
14,On-board Service,Satisfaction level with the on-boarding servic...
15,Seat Comfort,Satisfaction level with the comfort of the air...
16,Leg Room Service,Satisfaction level with the leg room of the ai...
17,Cleanliness,Satisfaction level with the cleanliness of the...
18,Food and Drink,Satisfaction level with the food and drinks on...
19,In-flight Service,Satisfaction level with the in-flight service ...
20,In-flight Wifi Service,Satisfaction level with the in-flight Wifi ser...
21,In-flight Entertainment,Satisfaction level with the in-flight entertai...
22,Baggage Handling,Satisfaction level with the baggage handling f...
23,Satisfaction,Overall satisfaction level with the airline (S...

In [6]:
rating_cols = [
    "departure_and_arrival_time_convenience",
    "ease_of_online_booking",
    "gate_location",
    "checkin_service",
    "online_boarding",
    "seat_comfort",
    "leg_room_service",
    "cleanliness",
    "food_and_drink",
    "inflight_entertainment",
    "inflight_wifi_service",
    "inflight_service",
    "baggage_handling",
    "on_board_service"
]

rating_cols = [
    col for col in rating_cols
    if col in df_clean.columns
]

for col in rating_cols:
    print(f"{col}:")
    print(df_clean[col].value_counts(dropna=False).sort_index())
    print()

departure_and_arrival_time_convenience:
departure_and_arrival_time_convenience
0     6681
1    19409
2    21534
3    22378
4    31880
5    27998
Name: count, dtype: int64

ease_of_online_booking:
ease_of_online_booking
0     5682
1    21886
2    30051
3    30393
4    24444
5    17424
Name: count, dtype: int64

gate_location:
gate_location
0        1
1    21991
2    24296
3    35717
4    30466
5    17409
Name: count, dtype: int64

online_boarding:
online_boarding
0     3080
1    13261
2    21934
3    27117
4    38468
5    26020
Name: count, dtype: int64

seat_comfort:
seat_comfort
0        1
1    15108
2    18529
3    23328
4    39756
5    33158
Name: count, dtype: int64

leg_room_service:
leg_room_service
0      598
1    12895
2    24540
3    25056
4    35886
5    30905
Name: count, dtype: int64

cleanliness:
cleanliness
0       14
1    16729
2    20113
3    30639
4    33969
5    28416
Name: count, dtype: int64

food_and_drink:
food_and_drink
0      132
1    16051
2    27383
3    27794
4    30563
5    27957
Name: count, dtype: int64

baggage_handling:
baggage_handling
1     9028
2    14362
3    25851
4    46761
5    33878
Name: count, dtype: int64

on_board_service:
on_board_service
0        5
1    14787
2    18351
3    28542
4    38703
5    29492
Name: count, dtype: int64

In [7]:
print("Missing departure delays:",
      df_clean["departure_delay"].isna().sum())

print("Missing arrival delays:",
      df_clean["arrival_delay"].isna().sum())

display(
    df_clean[["departure_delay", "arrival_delay"]].describe()
)

Missing departure delays: 0
Missing arrival delays: 393

       departure_delay  arrival_delay
count    129880.000000  129487.000000
mean         14.713713      15.091129
std          38.071126      38.465650
min           0.000000       0.000000
25%           0.000000       0.000000
50%           0.000000       0.000000
75%          12.000000      13.000000
max        1592.000000    1584.000000

In [8]:
processed_dir = data_dir / "processed"
processed_dir.mkdir(parents=True, exist_ok=True)

output_path = processed_dir / "airline_satisfaction_clean.csv"

df_clean.to_csv(output_path, index=False)

print("Saved to:", output_path)
print("Final shape:", df_clean.shape)

Saved to: c:\Users\HP\OneDrive\Desktop\Airline-Passenger-Satisfaction\data\processed\airline_satisfaction_clean.csv
Final shape: (129880, 24)

In [9]:
# Verify the cleaned dataset was saved
output_path = data_dir / "processed" / "airline_satisfaction_clean.csv"

print("File exists:", output_path.exists())

df_check = pd.read_csv(output_path)

print("Saved dataset shape:", df_check.shape)
print("Missing arrival delays:",
      df_check["arrival_delay"].isna().sum())

File exists: True
Saved dataset shape: (129880, 24)
Missing arrival delays: 393

In [11]:

import pandas as pd
from pathlib import Path

data_dir = Path("../data")

dictionary = pd.read_csv(data_dir / "data_dictionary.csv")

display(dictionary)

,Field,Description
0,ID,Unique passenger identifier
1,Gender,Gender of the passenger (Female/Male)
2,Age,Age of the passenger
3,Customer Type,Type of airline customer (First-time/Returning)
4,Type of Travel,Purpose of the flight (Business/Personal)
5,Class,Travel class in the airplane for the passenger...
6,Flight Distance,Flight distance in miles
7,Departure Delay,Flight departure delay in minutes
8,Arrival Delay,Flight arrival delay in minutes
9,Departure and Arrival Time Convenience,Satisfaction level with the convenience of the...
10,Ease of Online Booking,Satisfaction level with the online booking exp...
11,Check-in Service,Satisfaction level with the check-in service f...
12,Online Boarding,Satisfaction level with the online boarding ex...
13,Gate Location,Satisfaction level with the gate location in t...
14,On-board Service,Satisfaction level with the on-boarding servic...
15,Seat Comfort,Satisfaction level with the comfort of the air...
16,Leg Room Service,Satisfaction level with the leg room of the ai...
17,Cleanliness,Satisfaction level with the cleanliness of the...
18,Food and Drink,Satisfaction level with the food and drinks on...
19,In-flight Service,Satisfaction level with the in-flight service ...
20,In-flight Wifi Service,Satisfaction level with the in-flight Wifi ser...
21,In-flight Entertainment,Satisfaction level with the in-flight entertai...
22,Baggage Handling,Satisfaction level with the baggage handling f...
23,Satisfaction,Overall satisfaction level with the airline (S...

In [12]:

# Check the values used in service-rating columns

service_columns = [
    "departure_and_arrival_time_convenience",
    "ease_of_online_booking",
    "check_in_service",
    "online_boarding",
    "gate_location",
    "on_board_service",
    "seat_comfort",
    "leg_room_service",
    "cleanliness",
    "food_and_drink",
    "in_flight_service",
    "in_flight_wifi_service",
    "in_flight_entertainment",
    "baggage_handling"
]

for col in service_columns:
    print(f"\n{col}")
    print(df_clean[col].value_counts(dropna=False).sort_index())

departure_and_arrival_time_convenience
departure_and_arrival_time_convenience
0     6681
1    19409
2    21534
3    22378
4    31880
5    27998
Name: count, dtype: int64

ease_of_online_booking
ease_of_online_booking
0     5682
1    21886
2    30051
3    30393
4    24444
5    17424
Name: count, dtype: int64

check_in_service
check_in_service
0        1
1    16108
2    16102
3    35453
4    36333
5    25883
Name: count, dtype: int64

online_boarding
online_boarding
0     3080
1    13261
2    21934
3    27117
4    38468
5    26020
Name: count, dtype: int64

gate_location
gate_location
0        1
1    21991
2    24296
3    35717
4    30466
5    17409
Name: count, dtype: int64

on_board_service
on_board_service
0        5
1    14787
2    18351
3    28542
4    38703
5    29492
Name: count, dtype: int64

seat_comfort
seat_comfort
0        1
1    15108
2    18529
3    23328
4    39756
5    33158
Name: count, dtype: int64

leg_room_service
leg_room_service
0      598
1    12895
2    24540
3    25056
4    35886
5    30905
Name: count, dtype: int64

cleanliness
cleanliness
0       14
1    16729
2    20113
3    30639
4    33969
5    28416
Name: count, dtype: int64

food_and_drink
food_and_drink
0      132
1    16051
2    27383
3    27794
4    30563
5    27957
Name: count, dtype: int64

in_flight_service
in_flight_service
0        5
1     8862
2    14308
3    25316
4    47323
5    34066
Name: count, dtype: int64

in_flight_wifi_service
in_flight_wifi_service
0     3916
1    22328
2    32320
3    32185
4    24775
5    14356
Name: count, dtype: int64

in_flight_entertainment
in_flight_entertainment
0       18
1    15675
2    21968
3    23884
4    36791
5    31544
Name: count, dtype: int64

baggage_handling
baggage_handling
1     9028
2    14362
3    25851
4    46761
5    33878
Name: count, dtype: int64

In [14]:

dictionary[
    dictionary["Field"].str.contains(
        "convenience|booking|service|boarding|comfort|wifi|cleanliness|satisfaction",
        case=False,
        na=False
    )
]

,Field,Description
9,Departure and Arrival Time Convenience,Satisfaction level with the convenience of the...
10,Ease of Online Booking,Satisfaction level with the online booking exp...
11,Check-in Service,Satisfaction level with the check-in service f...
12,Online Boarding,Satisfaction level with the online boarding ex...
14,On-board Service,Satisfaction level with the on-boarding servic...
15,Seat Comfort,Satisfaction level with the comfort of the air...
16,Leg Room Service,Satisfaction level with the leg room of the ai...
17,Cleanliness,Satisfaction level with the cleanliness of the...
19,In-flight Service,Satisfaction level with the in-flight service ...
20,In-flight Wifi Service,Satisfaction level with the in-flight Wifi ser...
23,Satisfaction,Overall satisfaction level with the airline (S...

In [15]:

# Check whether passengers with a service rating of 0
# have a different overall satisfaction pattern.

check_columns = [
    "in_flight_wifi_service",
    "online_boarding",
    "seat_comfort",
    "cleanliness",
    "food_and_drink"
]

for col in check_columns:
    print(f"\n--- {col} ---")

    result = (
        df_clean.groupby(col, dropna=False)["satisfaction"]
        .value_counts(normalize=True)
        .mul(100)
        .round(2)
        .unstack(fill_value=0)
    )

    print(result)

--- in_flight_wifi_service ---
satisfaction            Neutral or Dissatisfied  Satisfied
in_flight_wifi_service
0                                          0.26      99.74
1                                         67.18      32.82
2                                         75.28      24.72
3                                         74.82      25.18
4                                         39.92      60.08
5                                          0.98      99.02

--- online_boarding ---
satisfaction     Neutral or Dissatisfied  Satisfied
online_boarding
0                                  43.54      56.46
1                                  86.22      13.78
2                                  88.55      11.45
3                                  86.24      13.76
4                                  37.70      62.30
5                                  12.94      87.06

--- seat_comfort ---
satisfaction  Neutral or Dissatisfied  Satisfied
seat_comfort
0                              100.00       0.00
1                               77.67      22.33
2                               77.40      22.60
3                               78.59      21.41
4                               43.97      56.03
5                               34.87      65.13

--- cleanliness ---
satisfaction  Neutral or Dissatisfied  Satisfied
cleanliness
0                              100.00       0.00
1                               80.30      19.70
2                               78.74      21.26
3                               56.69      43.31
4                               46.47      53.53
5                               38.75      61.25

--- food_and_drink ---
satisfaction    Neutral or Dissatisfied  Satisfied
food_and_drink
0                                 58.33      41.67
1                                 80.04      19.96
2                                 61.10      38.90
3                                 60.26      39.74
4                                 47.42      52.58
5                                 44.91      55.09

In [16]:

# Compare satisfaction by service rating and passenger class

for col in ["in_flight_wifi_service", "online_boarding"]:
    print(f"\n{'=' * 55}")
    print(f"Service: {col}")
    print("=" * 55)

    result = (
        df_clean.groupby(["class", col])["satisfaction"]
        .apply(lambda x: (x == "Satisfied").mean() * 100)
        .round(2)
        .rename("satisfaction_rate_pct")
        .reset_index()
    )

    print(result.to_string(index=False))

=======================================================
Service: in_flight_wifi_service
=======================================================
       class  in_flight_wifi_service  satisfaction_rate_pct
    Business                       0                 100.00
    Business                       1                  64.83
    Business                       2                  54.82
    Business                       3                  55.71
    Business                       4                  77.72
    Business                       5                  98.95
     Economy                       0                  99.66
     Economy                       1                   0.02
     Economy                       2                   2.07
     Economy                       3                   2.51
     Economy                       4                  42.87
     Economy                       5                  99.31
Economy Plus                       0                  97.67
Economy Plus                       1                   0.07
Economy Plus                       2                   3.10
Economy Plus                       3                   4.64
Economy Plus                       4                  49.52
Economy Plus                       5                  98.34

=======================================================
Service: online_boarding
=======================================================
       class  online_boarding  satisfaction_rate_pct
    Business                0                  80.44
    Business                1                  35.43
    Business                2                  27.37
    Business                3                  28.46
    Business                4                  80.71
    Business                5                  97.32
     Economy                0                  47.98
     Economy                1                   5.27
     Economy                2                   4.78
     Economy                3                   5.35
     Economy                4                  32.76
     Economy                5                  60.34
Economy Plus                0                  59.89
Economy Plus                1                   7.74
Economy Plus                2                   6.56
Economy Plus                3                   7.39
Economy Plus                4                  38.83
Economy Plus                5                  71.29

In [17]:

boarding_results = (
    df_clean.groupby(["class", "online_boarding"])
    .agg(
        total_passengers=("satisfaction", "size"),
        satisfied_passengers=(
            "satisfaction",
            lambda x: (x == "Satisfied").sum()
        )
    )
    .reset_index()
)

boarding_results["satisfaction_rate_pct"] = (
    boarding_results["satisfied_passengers"]
    / boarding_results["total_passengers"] * 100
).round(2)

display(boarding_results.to_string(index=False))

'       class  online_boarding  total_passengers  satisfied_passengers  satisfaction_rate_pct\n    Business                0               675                   543                  80.44\n    Business                1              3638                  1289                  35.43\n    Business                2              6316                  1729                  27.37\n    Business                3              9664                  2750                  28.46\n    Business                4             23422                 18905                  80.71\n    Business                5             18445                 17950                  97.32\n     Economy                0              2051                   984                  47.98\n     Economy                1              8357                   440                   5.27\n     Economy                2             13560                   648                   4.78\n     Economy                3             15097                   808                   5.35\n     Economy                4             12867                  4215                  32.76\n     Economy                5              6377                  3848                  60.34\nEconomy Plus                0               354                   212                  59.89\nEconomy Plus                1              1266                    98                   7.74\nEconomy Plus                2              2058                   135                   6.56\nEconomy Plus                3              2356                   174                   7.39\nEconomy Plus                4              2179                   846                  38.83\nEconomy Plus                5              1198                   854                  71.29'

In [18]:

# Compare low ratings (1–3) for WiFi and online boarding by class.
# Rating 0 is excluded until its meaning is confirmed.

services = {
    "WiFi": "in_flight_wifi_service",
    "Online Boarding": "online_boarding",
}

rows = []

for service_name, col in services.items():
    temp = df_clean[df_clean[col].between(1, 3)]

    summary = (
        temp.groupby("class")
        .agg(
            passengers=("satisfaction", "size"),
            satisfied=("satisfaction",
                       lambda x: (x == "Satisfied").sum())
        )
        .reset_index()
    )

    summary["service"] = service_name
    summary["dissatisfied_pct"] = (
        100 * (summary["passengers"] - summary["satisfied"])
        / summary["passengers"]
    ).round(2)

    rows.append(summary)

comparison = pd.concat(rows, ignore_index=True)

display(
    comparison[
        ["service", "class", "passengers", "dissatisfied_pct"]
    ].sort_values(["class", "service"]).to_string(index=False)
)

'        service        class  passengers  dissatisfied_pct\nOnline Boarding     Business       19618             70.60\n           WiFi     Business       38748             41.95\nOnline Boarding      Economy       37014             94.88\n           WiFi      Economy       41773             98.23\nOnline Boarding Economy Plus        5680             92.83\n           WiFi Economy Plus        6312             97.01'

In [19]:

# Compare satisfaction by departure-delay band

df_delay = df_clean.copy()

df_delay["departure_delay_band"] = pd.cut(
    df_delay["departure_delay"],
    bins=[-float("inf"), 0, 15, 30, 60, float("inf")],
    labels=[
        "No delay",
        "1–15 minutes",
        "16–30 minutes",
        "31–60 minutes",
        "Over 60 minutes"
    ]
)

delay_summary = (
    df_delay.groupby("departure_delay_band", observed=False)
    .agg(
        passengers=("satisfaction", "size"),
        satisfied=("satisfaction",
                   lambda x: (x == "Satisfied").sum())
    )
    .reset_index()
)

delay_summary["satisfaction_rate_pct"] = (
    100 * delay_summary["satisfied"]
    / delay_summary["passengers"]
).round(2)

display(delay_summary.to_string(index=False))

'departure_delay_band  passengers  satisfied  satisfaction_rate_pct\n            No delay       73356      33699                  45.94\n        1–15 minutes       27787      12100                  43.55\n       16–30 minutes       10639       4089                  38.43\n       31–60 minutes        9123       3322                  36.41\n     Over 60 minutes        8975       3218                  35.86'

In [20]:

df_arrival = df_clean.copy()

df_arrival["arrival_delay_band"] = pd.cut(
    df_arrival["arrival_delay"],
    bins=[-float("inf"), 0, 15, 30, 60, float("inf")],
    labels=[
        "No delay",
        "1–15 minutes",
        "16–30 minutes",
        "31–60 minutes",
        "Over 60 minutes"
    ]
)

arrival_summary = (
    df_arrival.groupby("arrival_delay_band", observed=False)
    .agg(
        passengers=("satisfaction", "count"),
        satisfied=("satisfaction",
                   lambda x: (x == "Satisfied").sum())
    )
    .reset_index()
)

arrival_summary["satisfaction_rate_pct"] = (
    100 * arrival_summary["satisfied"]
    / arrival_summary["passengers"]
).round(2)

display(arrival_summary.to_string(index=False))

'arrival_delay_band  passengers  satisfied  satisfaction_rate_pct\n          No delay       72753      34490                  47.41\n      1–15 minutes       27176      11194                  41.19\n     16–30 minutes       11183       3997                  35.74\n     31–60 minutes        9287       3348                  36.05\n   Over 60 minutes        9088       3233                  35.57'

In [21]:

import pandas as pd

service_columns = [
    "departure_and_arrival_time_convenience",
    "ease_of_online_booking",
    "check_in_service",
    "online_boarding",
    "gate_location",
    "on_board_service",
    "seat_comfort",
    "leg_room_service",
    "cleanliness",
    "food_and_drink",
    "in_flight_service",
    "in_flight_wifi_service",
    "in_flight_entertainment",
    "baggage_handling"
]

df_driver = df_clean.copy()

df_driver["satisfied_flag"] = (
    df_driver["satisfaction"] == "Satisfied"
).astype(int)

driver_results = []

for col in service_columns:
    valid = df_driver[[col, "satisfied_flag"]].dropna()

    driver_results.append({
        "service": col,
        "spearman_correlation": valid[col].corr(
            valid["satisfied_flag"], method="spearman"
        ),
        "average_rating": valid[col].mean(),
        "passengers": len(valid)
    })

driver_summary = pd.DataFrame(driver_results)

driver_summary["spearman_correlation"] = (
    driver_summary["spearman_correlation"].round(3)
)
driver_summary["average_rating"] = (
    driver_summary["average_rating"].round(2)
)

display(
    driver_summary.sort_values(
        "spearman_correlation", ascending=False
    ).to_string(index=False)
)

'                               service  spearman_correlation  average_rating  passengers\n                       online_boarding                 0.550            3.25      129880\n               in_flight_entertainment                 0.400            3.36      129880\n                          seat_comfort                 0.362            3.44      129880\n                      on_board_service                 0.328            3.38      129880\n                      leg_room_service                 0.317            3.35      129880\n                           cleanliness                 0.305            3.29      129880\n                in_flight_wifi_service                 0.287            2.73      129880\n                      baggage_handling                 0.271            3.63      129880\n                     in_flight_service                 0.266            3.64      129880\n                      check_in_service                 0.234            3.31      129880\n                        food_and_drink                 0.209            3.20      129880\n                ease_of_online_booking                 0.174            2.76      129880\n                         gate_location                -0.003            2.98      129880\ndeparture_and_arrival_time_convenience                -0.052            3.06      129880'

In [22]:

# Combine satisfaction association and service performance

priority = driver_summary.copy()

priority["service"] = priority["service"].str.replace(
    "_", " ", regex=False
).str.title()

priority["importance_rank"] = priority[
    "spearman_correlation"
].rank(ascending=False, method="min").astype(int)

priority["performance_rank"] = priority[
    "average_rating"
].rank(ascending=True, method="min").astype(int)

display(
    priority.sort_values(
        ["importance_rank", "performance_rank"]
    )[
        [
            "service",
            "spearman_correlation",
            "average_rating",
            "importance_rank",
            "performance_rank"
        ]
    ].to_string(index=False)
)

'                               service  spearman_correlation  average_rating  importance_rank  performance_rank\n                       Online Boarding                 0.550            3.25                1                 6\n               In Flight Entertainment                 0.400            3.36                2                10\n                          Seat Comfort                 0.362            3.44                3                12\n                      On Board Service                 0.328            3.38                4                11\n                      Leg Room Service                 0.317            3.35                5                 9\n                           Cleanliness                 0.305            3.29                6                 7\n                In Flight Wifi Service                 0.287            2.73                7                 1\n                      Baggage Handling                 0.271            3.63                8                13\n                     In Flight Service                 0.266            3.64                9                14\n                      Check In Service                 0.234            3.31               10                 8\n                        Food And Drink                 0.209            3.20               11                 5\n                Ease Of Online Booking                 0.174            2.76               12                 2\n                         Gate Location                -0.003            2.98               13                 3\nDeparture And Arrival Time Convenience                -0.052            3.06               14                 4'

In [23]:

# Estimate how widespread low service ratings are.
# Ratings 1–3 are used; rating 0 is excluded pending validation.

service_columns = [
    "online_boarding",
    "in_flight_entertainment",
    "seat_comfort",
    "on_board_service",
    "leg_room_service",
    "cleanliness",
    "in_flight_wifi_service",
    "baggage_handling",
    "in_flight_service",
    "check_in_service",
    "food_and_drink",
    "ease_of_online_booking",
    "gate_location",
    "departure_and_arrival_time_convenience"
]

reach_rows = []

for col in service_columns:
    ratings = df_clean[col]
    valid = ratings.notna()
    low = ratings.between(1, 3)

    reach_rows.append({
        "service": col.replace("_", " ").title(),
        "valid_passengers": int(valid.sum()),
        "low_rating_passengers": int(low.sum()),
        "low_rating_pct": round(
            100 * low.sum() / valid.sum(), 2
        )
    })

reach_summary = pd.DataFrame(reach_rows)

display(
    reach_summary.sort_values(
        "low_rating_passengers", ascending=False
    ).to_string(index=False)
)

'                               service  valid_passengers  low_rating_passengers  low_rating_pct\n                In Flight Wifi Service            129880                  86833           66.86\n                Ease Of Online Booking            129880                  82330           63.39\n                         Gate Location            129880                  82004           63.14\n                        Food And Drink            129880                  71228           54.84\n                      Check In Service            129880                  67663           52.10\n                           Cleanliness            129880                  67481           51.96\nDeparture And Arrival Time Convenience            129880                  63321           48.75\n                      Leg Room Service            129880                  62491           48.11\n                       Online Boarding            129880                  62312           47.98\n                      On Board Service            129880                  61680           47.49\n               In Flight Entertainment            129880                  61527           47.37\n                          Seat Comfort            129880                  56965           43.86\n                      Baggage Handling            129880                  49241           37.91\n                     In Flight Service            129880                  48486           37.33'

In [24]:

for col in service_columns:
    zero_group = df_clean[df_clean[col] == 0]

    if len(zero_group) > 0:
        satisfaction_rate = (
            zero_group["satisfaction"].eq("Satisfied").mean() * 100
        )

        print(
            f"{col}: "
            f"{len(zero_group):,} zero ratings, "
            f"{satisfaction_rate:.2f}% satisfied"
        )

online_boarding: 3,080 zero ratings, 56.46% satisfied
in_flight_entertainment: 18 zero ratings, 0.00% satisfied
seat_comfort: 1 zero ratings, 0.00% satisfied
on_board_service: 5 zero ratings, 0.00% satisfied
leg_room_service: 598 zero ratings, 34.45% satisfied
cleanliness: 14 zero ratings, 0.00% satisfied
in_flight_wifi_service: 3,916 zero ratings, 99.74% satisfied
in_flight_service: 5 zero ratings, 0.00% satisfied
check_in_service: 1 zero ratings, 0.00% satisfied
food_and_drink: 132 zero ratings, 41.67% satisfied
ease_of_online_booking: 5,682 zero ratings, 66.56% satisfied
gate_location: 1 zero ratings, 100.00% satisfied
departure_and_arrival_time_convenience: 6,681 zero ratings, 48.11% satisfied

In [25]:

# Check the data dictionary for the exact descriptions
# of service-rating fields.

display(dictionary.to_string(index=False))

'                                 Field                                                                                                                                 Description\n                                    ID                                                                                                                 Unique passenger identifier\n                                Gender                                                                                                       Gender of the passenger (Female/Male)\n                                   Age                                                                                                                        Age of the passenger\n                         Customer Type                                                                                             Type of airline customer (First-time/Returning)\n                        Type of Travel                                                                                                   Purpose of the flight (Business/Personal)\n                                 Class                                                                                         Travel class in the airplane for the passenger seat\n                       Flight Distance                                                                                                                    Flight distance in miles\n                       Departure Delay                                                                                                           Flight departure delay in minutes\n                         Arrival Delay                                                                                                             Flight arrival delay in minutes\nDeparture and Arrival Time Convenience Satisfaction level with the convenience of the flight departure and arrival times from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                Ease of Online Booking                             Satisfaction level with the online booking experience from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                      Check-in Service                                      Satisfaction level with the check-in service from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                       Online Boarding                            Satisfaction level with the online boarding experience from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                         Gate Location                          Satisfaction level with the gate location in the airport from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                      On-board Service                    Satisfaction level with the on-boarding service in the airport from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                          Seat Comfort                          Satisfaction level with the comfort of the airplane seat from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                      Leg Room Service                         Satisfaction level with the leg room of the airplane seat from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                           Cleanliness                           Satisfaction level with the cleanliness of the airplane from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                        Food and Drink                       Satisfaction level with the food and drinks on the airplane from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                     In-flight Service                                     Satisfaction level with the in-flight service from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                In-flight Wifi Service                                Satisfaction level with the in-flight Wifi service from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n               In-flight Entertainment                               Satisfaction level with the in-flight entertainment from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                      Baggage Handling                     Satisfaction level with the baggage handling from the airline from 1 (lowest) to 5 (highest) - 0 means "not applicable"\n                          Satisfaction                                                              Overall satisfaction level with the airline (Satisfied/Neutral or unsatisfied)'

In [26]:

# Recalculate service correlations excluding "not applicable" ratings (0)

service_columns = [
    "departure_and_arrival_time_convenience",
    "ease_of_online_booking",
    "check_in_service",
    "online_boarding",
    "gate_location",
    "on_board_service",
    "seat_comfort",
    "leg_room_service",
    "cleanliness",
    "food_and_drink",
    "in_flight_service",
    "in_flight_wifi_service",
    "in_flight_entertainment",
    "baggage_handling"
]

df_driver = df_clean.copy()

df_driver["satisfied_flag"] = (
    df_driver["satisfaction"] == "Satisfied"
).astype(int)

driver_results = []

for col in service_columns:
    valid = df_driver.loc[
        df_driver[col].between(1, 5),
        [col, "satisfied_flag"]
    ]

    driver_results.append({
        "service": col,
        "spearman_correlation": valid[col].corr(
            valid["satisfied_flag"], method="spearman"
        ),
        "average_rating": valid[col].mean(),
        "passengers_rated": len(valid),
        "not_applicable": int((df_driver[col] == 0).sum())
    })

driver_summary = pd.DataFrame(driver_results)

driver_summary["spearman_correlation"] = (
    driver_summary["spearman_correlation"].round(3)
)
driver_summary["average_rating"] = (
    driver_summary["average_rating"].round(2)
)

display(
    driver_summary.sort_values(
        "spearman_correlation", ascending=False
    ).to_string(index=False)
)

'                               service  spearman_correlation  average_rating  passengers_rated  not_applicable\n                       online_boarding                 0.590            3.33            126800            3080\n               in_flight_entertainment                 0.400            3.36            129862              18\n                in_flight_wifi_service                 0.372            2.81            125964            3916\n                          seat_comfort                 0.362            3.44            129879               1\n                      on_board_service                 0.328            3.38            129875               5\n                      leg_room_service                 0.319            3.37            129282             598\n                           cleanliness                 0.305            3.29            129866              14\n                      baggage_handling                 0.271            3.63            129880               0\n                     in_flight_service                 0.266            3.64            129875               5\n                      check_in_service                 0.234            3.31            129879               1\n                ease_of_online_booking                 0.232            2.88            124198            5682\n                        food_and_drink                 0.209            3.21            129748             132\n                         gate_location                -0.003            2.98            129879               1\ndeparture_and_arrival_time_convenience                -0.049            3.22            123199            6681'

In [27]:

df_segments = df_clean.copy()

df_segments["age_band"] = pd.cut(
    df_segments["age"],
    bins=[0, 25, 40, 60, float("inf")],
    labels=["18–25", "26–40", "41–60", "60+"],
    include_lowest=True
)

segment_columns = [
    "class",
    "type_of_travel",
    "customer_type",
    "age_band"
]

for col in segment_columns:
    print(f"\nSatisfaction by {col}")

    result = (
        df_segments.groupby(col, observed=False)
        .agg(
            passengers=("satisfaction", "size"),
            satisfied=("satisfaction",
                       lambda x: (x == "Satisfied").sum())
        )
        .reset_index()
    )

    result["satisfaction_rate_pct"] = (
        100 * result["satisfied"] / result["passengers"]
    ).round(2)

    display(result.to_string(index=False))

Satisfaction by class

'       class  passengers  satisfied  satisfaction_rate_pct\n    Business       62160      43166                  69.44\n     Economy       58309      10943                  18.77\nEconomy Plus        9411       2319                  24.64'

Satisfaction by type_of_travel

'type_of_travel  passengers  satisfied  satisfaction_rate_pct\n      Business       89693      52356                  58.37\n      Personal       40187       4072                  10.13'

Satisfaction by customer_type

'customer_type  passengers  satisfied  satisfaction_rate_pct\n   First-time       23780       5700                  23.97\n    Returning      106100      50728                  47.81'

Satisfaction by age_band

'age_band  passengers  satisfied  satisfaction_rate_pct\n   18–25       28173       8005                  28.41\n   26–40       39099      16027                  40.99\n   41–60       52554      30303                  57.66\n     60+       10054       2093                  20.82'

In [28]:

service_columns = [
    "online_boarding",
    "in_flight_entertainment",
    "in_flight_wifi_service",
    "seat_comfort",
    "on_board_service",
    "leg_room_service",
    "cleanliness",
    "baggage_handling",
    "in_flight_service",
    "check_in_service",
    "food_and_drink",
    "ease_of_online_booking"
]

segment_driver_rows = []

for passenger_class in df_clean["class"].dropna().unique():
    class_df = df_clean[df_clean["class"] == passenger_class]

    for col in service_columns:
        valid = class_df.loc[
            class_df[col].between(1, 5),
            [col, "satisfaction"]
        ]

        satisfaction_flag = (
            valid["satisfaction"] == "Satisfied"
        ).astype(int)

        segment_driver_rows.append({
            "class": passenger_class,
            "service": col,
            "correlation": valid[col].corr(
                satisfaction_flag, method="spearman"
            ),
            "average_rating": valid[col].mean(),
            "passengers_rated": len(valid)
        })

segment_drivers = pd.DataFrame(segment_driver_rows)

segment_drivers["correlation"] = (
    segment_drivers["correlation"].round(3)
)
segment_drivers["average_rating"] = (
    segment_drivers["average_rating"].round(2)
)

display(
    segment_drivers.sort_values(
        ["class", "correlation"], ascending=[True, False]
    ).to_string(index=False)
)

'       class                 service  correlation  average_rating  passengers_rated\n    Business         online_boarding        0.572            3.76             61485\n    Business in_flight_entertainment        0.491            3.64             62152\n    Business            seat_comfort        0.448            3.76             62159\n    Business        on_board_service        0.423            3.68             62155\n    Business        leg_room_service        0.415            3.66             62002\n    Business             cleanliness        0.388            3.48             62156\n    Business        baggage_handling        0.378            3.84             62160\n    Business       in_flight_service        0.378            3.85             62155\n    Business        check_in_service        0.318            3.52             62159\n    Business  in_flight_wifi_service        0.244            2.89             59670\n    Business          food_and_drink        0.217            3.33             62123\n    Business  ease_of_online_booking        0.116            3.04             59534\n     Economy  in_flight_wifi_service        0.582            2.73             57140\n     Economy         online_boarding        0.420            2.92             56258\n     Economy  ease_of_online_booking        0.317            2.72             55706\n     Economy in_flight_entertainment        0.185            3.10             58305\n     Economy          food_and_drink        0.147            3.09             58236\n     Economy             cleanliness        0.138            3.11             58305\n     Economy            seat_comfort        0.127            3.14             58309\n     Economy        on_board_service        0.076            3.12             58309\n     Economy        leg_room_service        0.076            3.10             57923\n     Economy        check_in_service        0.038            3.12             58309\n     Economy        baggage_handling        0.028            3.45             58309\n     Economy       in_flight_service        0.025            3.47             58309\nEconomy Plus  in_flight_wifi_service        0.638            2.83              9154\nEconomy Plus         online_boarding        0.468            3.00              9057\nEconomy Plus in_flight_entertainment        0.332            3.12              9405\nEconomy Plus          food_and_drink        0.268            3.12              9389\nEconomy Plus             cleanliness        0.264            3.12              9405\nEconomy Plus            seat_comfort        0.238            3.17              9411\nEconomy Plus  ease_of_online_booking        0.211            2.80              8958\nEconomy Plus        on_board_service        0.074            3.04              9411\nEconomy Plus        leg_room_service        0.074            3.07              9357\nEconomy Plus        check_in_service        0.037            3.01              9411\nEconomy Plus        baggage_handling       -0.006            3.35              9411\nEconomy Plus       in_flight_service       -0.014            3.38              9411'

In [29]:

age_results = (
    df_segments.groupby("age_band", observed=False)
    .agg(
        passengers=("satisfaction", "size"),
        satisfied=("satisfaction",
                   lambda x: (x == "Satisfied").sum())
    )
    .reset_index()
)

age_results["satisfaction_rate_pct"] = (
    100 * age_results["satisfied"] / age_results["passengers"]
).round(2)

display(age_results.to_string(index=False))

'age_band  passengers  satisfied  satisfaction_rate_pct\n   18–25       28173       8005                  28.41\n   26–40       39099      16027                  40.99\n   41–60       52554      30303                  57.66\n     60+       10054       2093                  20.82'

In [30]:

delay_by_class = df_clean.copy()

delay_by_class["departure_delay_band"] = pd.cut(
    delay_by_class["departure_delay"],
    bins=[-float("inf"), 0, 15, 30, 60, float("inf")],
    labels=[
        "No delay",
        "1–15 minutes",
        "16–30 minutes",
        "31–60 minutes",
        "Over 60 minutes"
    ]
)

result = (
    delay_by_class.groupby(
        ["class", "departure_delay_band"],
        observed=False
    )
    .agg(
        passengers=("satisfaction", "size"),
        satisfied=("satisfaction",
                   lambda x: (x == "Satisfied").sum())
    )
    .reset_index()
)

result["satisfaction_rate_pct"] = (
    100 * result["satisfied"] / result["passengers"]
).round(2)

display(result.to_string(index=False))

'       class departure_delay_band  passengers  satisfied  satisfaction_rate_pct\n    Business             No delay       35032      25042                  71.48\n    Business         1–15 minutes       13638       9535                  69.91\n    Business        16–30 minutes        5160       3386                  65.62\n    Business        31–60 minutes        4245       2681                  63.16\n    Business      Over 60 minutes        4085       2522                  61.74\n     Economy             No delay       33079       7131                  21.56\n     Economy         1–15 minutes       12151       2117                  17.42\n     Economy        16–30 minutes        4723        586                  12.41\n     Economy        31–60 minutes        4156        530                  12.75\n     Economy      Over 60 minutes        4200        579                  13.79\nEconomy Plus             No delay        5245       1526                  29.09\nEconomy Plus         1–15 minutes        1998        448                  22.42\nEconomy Plus        16–30 minutes         756        117                  15.48\nEconomy Plus        31–60 minutes         722        111                  15.37\nEconomy Plus      Over 60 minutes         690        117                  16.96'

In [31]:

# Build a preliminary candidate ranking from existing results

candidates = driver_summary[
    ["service", "spearman_correlation",
     "average_rating", "passengers_rated"]
].copy()

candidates["service"] = candidates["service"].str.replace(
    "_", " ", regex=False
).str.title()

candidates["low_rating_passengers"] = candidates["service"].map(
    reach_summary.set_index(
        reach_summary["service"].str.replace(
            "_", " ", regex=False
        ).str.title()
    )["low_rating_passengers"]
)

display(
    candidates.sort_values(
        "spearman_correlation", ascending=False
    ).to_string(index=False)
)

'                               service  spearman_correlation  average_rating  passengers_rated  low_rating_passengers\n                       Online Boarding                 0.590            3.33            126800                  62312\n               In Flight Entertainment                 0.400            3.36            129862                  61527\n                In Flight Wifi Service                 0.372            2.81            125964                  86833\n                          Seat Comfort                 0.362            3.44            129879                  56965\n                      On Board Service                 0.328            3.38            129875                  61680\n                      Leg Room Service                 0.319            3.37            129282                  62491\n                           Cleanliness                 0.305            3.29            129866                  67481\n                      Baggage Handling                 0.271            3.63            129880                  49241\n                     In Flight Service                 0.266            3.64            129875                  48486\n                      Check In Service                 0.234            3.31            129879                  67663\n                Ease Of Online Booking                 0.232            2.88            124198                  82330\n                        Food And Drink                 0.209            3.21            129748                  71228\n                         Gate Location                -0.003            2.98            129879                  82004\nDeparture And Arrival Time Convenience                -0.049            3.22            123199                  63321'

In [32]:

# Build a transparent screening score for service priorities.
# This is NOT a causal impact or ROI estimate.

priority = driver_summary.copy()

priority["service"] = priority["service"].str.replace(
    "_", " ", regex=False
).str.title()

reach = reach_summary.copy()
reach["service"] = reach["service"].str.replace(
    "_", " ", regex=False
).str.title()

priority = priority.merge(
    reach[["service", "low_rating_pct"]],
    on="service",
    how="left"
)

# Normalize importance to 0–1 across services
priority["importance_score"] = (
    priority["spearman_correlation"]
    - priority["spearman_correlation"].min()
) / (
    priority["spearman_correlation"].max()
    - priority["spearman_correlation"].min()
)

# Normalize performance gap and low-rating reach to 0–1
priority["performance_gap_score"] = (
    5 - priority["average_rating"]
) / 4

priority["reach_score"] = priority["low_rating_pct"] / 100

# Equal weights for an initial transparent screening score
priority["screening_score"] = 100 * (
    priority["importance_score"] / 3
    + priority["performance_gap_score"] / 3
    + priority["reach_score"] / 3
)

display(
    priority.sort_values(
        "screening_score", ascending=False
    )[
        [
            "service",
            "spearman_correlation",
            "average_rating",
            "low_rating_pct",
            "screening_score"
        ]
    ].round(2).to_string(index=False)
)

'                               service  spearman_correlation  average_rating  low_rating_pct  screening_score\n                       Online Boarding                  0.59            3.33           47.98            63.24\n                In Flight Wifi Service                  0.37            2.81           66.86            62.50\n                Ease Of Online Booking                  0.23            2.88           63.39            53.45\n               In Flight Entertainment                  0.40            3.36           47.37            52.88\n                           Cleanliness                  0.30            3.29           51.96            50.04\n                          Seat Comfort                  0.36            3.44           43.86            49.06\n                      On Board Service                  0.33            3.38           47.49            49.00\n                      Leg Room Service                  0.32            3.37           48.11            48.82\n                        Food And Drink                  0.21            3.21           54.84            46.66\n                      Check In Service                  0.23            3.31           52.10            46.21\n                      Baggage Handling                  0.27            3.63           37.91            40.75\n                         Gate Location                 -0.00            2.98           63.14            40.28\n                     In Flight Service                  0.27            3.64           37.33            40.21\nDeparture And Arrival Time Convenience                 -0.05            3.22           48.75            31.08'